services:
  shopnest:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: shopnest-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true # hot reload fix for macOS
    restart: unless-stopped
