import { Outfit } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
const outfit = Outfit({ subsets: ["latin"], weight: ["400", "700"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={outfit.className}
    >
      <body className="min-h-full flex flex-col">
        <ToastContainer />
        {children}

      </body>
    </html>
  );
}
